-- return {
--   "xiyaowong/transparent.nvim",
--   config = function()
--     require("transparent").setup({
--       extra_groups = {
--         "SignColumn", "EndOfBuffer"
--       },
--       exclude = { "StatusLine", "StatusLineNC" }
--     })
--   end,
-- }